library(rmarkdown)

render("exercises_meeting_1.Rmd")
render("exercises_meeting_2.Rmd")
render("exercises_meeting_3.Rmd")
render("exercises_meeting_4.Rmd")
render("exercises_meeting_5.Rmd")
render("exercises_meeting_6.Rmd")
render("exercises_meeting_7.Rmd")
render("exercises_meeting_8.Rmd")

render("spss_session_1.Rmd")
render("spss_session_2.Rmd")
render("spss_session_3.Rmd")
render("spss_session_4.Rmd")
